POST http://localhost:5000/users
Content-Type: application/json 

{   
    "name":"José García",
    "username": "jgarcia",
    "password":"987654321",
    "email":"jg@gmail.com",
    "role":"admin"
}



